Attribute VB_Name = "xlwings_udfs"
'Autogenerated code by xlwings - changes will be lost with next import!
Function CORREL2(x)
Attribute CORREL2.VB_Description = "Like CORREL, but as array formula for more than 2 data sets"
Attribute CORREL2.VB_ProcData.VB_Invoke_Func = " \n21"
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        CORREL2 = Py.CallUDF("TC", "CORREL2", Array(x), ThisWorkbook, Application.Caller)
        Exit Function
failed:
        CORREL2 = err.Description
End Function

Function add_one(data)
Attribute add_one.VB_Description = "Adds 1 to every cell in Range"
Attribute add_one.VB_ProcData.VB_Invoke_Func = " \n21"
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        add_one = Py.CallUDF("TC", "add_one", Array(data), ThisWorkbook, Application.Caller)
        Exit Function
failed:
        add_one = err.Description
End Function

Function double_sum(x, y)
Attribute double_sum.VB_Description = "Returns twice the sum of the two arguments"
Attribute double_sum.VB_ProcData.VB_Invoke_Func = " \n21"
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        double_sum = Py.CallUDF("TC", "double_sum", Array(x, y), ThisWorkbook, Application.Caller)
        Exit Function
failed:
        double_sum = err.Description
End Function

Sub get_workbook_name()
Attribute get_workbook_name.VB_Description = "Writes the name of the Workbook into Range(""D3"") of Sheet 1"
Attribute get_workbook_name.VB_ProcData.VB_Invoke_Func = " \n21"
        Py.CallUDF "TC", "get_workbook_name", Array(), ThisWorkbook, Application.Caller
End Sub

Function matrix_mult(x, y)
Attribute matrix_mult.VB_Description = "Alternative implementation of Excel's MMULT, requires NumPy"
Attribute matrix_mult.VB_ProcData.VB_Invoke_Func = " \n21"
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        matrix_mult = Py.CallUDF("TC", "matrix_mult", Array(x, y), ThisWorkbook, Application.Caller)
        Exit Function
failed:
        matrix_mult = err.Description
End Function

Function thisishello()
Attribute thisishello.VB_Description = "Python function 'thisishello' defined in 'z:\\my drive\\_storage\\backup\\documents\\ramdisk_loc\\documents\\root\\data\\TC.py'."
Attribute thisishello.VB_ProcData.VB_Invoke_Func = " \n21"
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        thisishello = Py.CallUDF("TC", "thisishello", Array(), ThisWorkbook, Application.Caller)
        Exit Function
failed:
        thisishello = err.Description
End Function

